# Generated by Django 5.1.1 on 2025-02-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_companywallet_alter_user_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
